stages:
  - test
  - deploy

grafana-monitoring-vm-1:
  trigger:
    include:
      - local: deployments/monitoring-vm-1/.gitlab-ci.yml

grafana-dev-2-vm-1:
  trigger:
    include:
      - local: deployments/dev-2-vm-1/.gitlab-ci.yml