stages:
  - test
  - deploy

grafana-monitoring-vm-1:
  trigger:
    include:
      - local: deployments/monitoring-vm-1/.gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - 'deployments/monitoring-vm-1/**/*'
    - when: manual

grafana-dev-2-vm-1:
  trigger:
    include:
      - local: deployments/dev-2-vm-1/.gitlab-ci.yml
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - 'deployments/dev-2-vm-1/**/*'
    - when: manual